### ISSUE TITLE
Incompatibility with Optifine notice

### ISSUE THREAD

**Issue by MichaelHillcox** [AdvancedXRay/XRay-Mod#140]
For a long time now this mod has not worked with Optifine, this has not changed unfortunitly. I have created an issue on the Optifine repo but have yet to hear back. I will keep this issue up to date with future issues with optifine and with any updates from the original issue created on the Optifine github.

### Issue
https://github.com/sp614x/optifine/issues/4357

### Notes and quirks
- Optifine typically works with this mod if you don't use shaders
- Sometimes shaders will not cause a problem and thus you will not have this issue
- Optiforge may resolve any issues you have but I can't confirm this.
- No I can't fix this from my side until I know what I should do from the Mod Dev himself as he's the only one that knows how Optifine works as it's a closed source mod.

**Comment by AngellusMortis** [comment]
This mod works with shaders just fine for me and some something kind of similar.

https://www.curseforge.com/minecraft/mc-mods/light-overlay
https://github.com/shedaniel/LightOverlay

It is specifically the "shows numbers instead" mode.

**Comment by MdBourg98** [comment]
Has any progress been made on this issue?

**Comment by lMagickl** [comment]
Did someone found a solution or fixed this ?
