### ISSUE TITLE
Xray keep crashing my game

### ISSUE THREAD

**Issue by Towhead1212** [AdvancedXRay/XRay-Mod#153]
**Describe the bug**
A clear and concise description of what the bug is. My minecraft wont start with the 1.6.0 version 

**To Reproduce**
1. Install the Direwolf20 1.12.2 pack with xray in it
2. Start the game

**Expected behavior**
The Game to Get past the loading screen.

**Minecraft Enviorment**
 - Minecraft Version: 1.12.2
 - XRay Mod Version: 1.6.0
 - Mod Pack & Version if applicable Direwolf20 1.12.2 2.7.0 
 - Forge Version if applicable 14.23.5.2854

**Additional context**
It had worked before now it wont start

**Comment by MichaelHillcox** [comment]
Crash log please

**Comment by MichaelHillcox** [comment]
Please reopen if you have a crashlog

**Comment by Towhead1212** [comment]
i have a crashlog
[crash-2020-10-19_18.48.09-client.txt](https://github.com/MichaelHillcox/XRay-Mod/files/5405441/crash-2020-10-19_18.48.09-client.txt)

**Comment by MichaelHillcox** [comment]
1.12 is no longer supported, sorry.
