### ISSUE TITLE
[1.16.3] Visual conflict with Advanced XRay mod

### ISSUE THREAD

**Issue by odisies9000** [AdvancedXRay/XRay-Mod#167]
I've noticed that while the x-ray mod is active, showing where the selected ore is, the mining gadget laser doesn't render.
You can see for yourself in the short youtube clip I've attached.
This is using the latest versions of both mods.
Video link : https://youtu.be/gOz40wUh4J0

Sorry for the late transfer

**Comment by MichaelHillcox** [comment]
This should be fixed for newer, supported, versions
