### ISSUE TITLE
Unplayable 1.12.2 forge

### ISSUE THREAD

**Issue by truidie213** [AdvancedXRay/XRay-Mod#184]
**Describe the bug**
The most recent "Advanced XRay // MC1.12.2 - 1.6.0" isn't playable
To Reproduce**
       **How I did it**
 Load Minecraft with the mod.

       **Expected behavior**
I expected it to load Minecraft
 but it just gave me a crash log.

**Screenshots**
https://user-images.githubusercontent.com/87638098/126120800-1475cf20-9da9-49f2-9b6e-d9f71a982d51.png
**Crash Log**
https://github.com/MichaelHillcox/XRay-Mod/files/6838818/screenshot.txt

**Comment by RuukasuGIT** [comment]
This has happened to me a few times now.
Resetting the config files seems to fix it, and I've decided that whenever I stop playing to remove any modded blocks that I am x-raying. This fixes the issue for me however it is unnecessarily thorough and is only a temporary fix, so you can play until the mod author replies.

**Comment by MichaelHillcox** [comment]
I wasn't aware this was still an issue, that error specifically is because an older version of the mod has been used and I had a poor migration system in place. If you're having another error, please share it here and I'll look into it

**Comment by MichaelHillcox** [comment]
1.12 is no longer supported.
