### ISSUE TITLE
Ore outlines prevent FTB Ultimine from marking mining area

### ISSUE THREAD

**Issue by shinji257** [AdvancedXRay/XRay-Mod#185]
**Describe the bug**
When xray is enabled it stops FTB Ultimine from showing the outline where you will be excavating at.

**To Reproduce**
1. Use a Forge pack that has Ultimine installed in it.  For me it is Enigmatica 6 right now.
2. Install the mode, enable it and set it to mark some ores
3. Hold down the excavate key so that FTB Ultimine marks the excavation area.

**Expected behavior**
Ores are marked but FTB Ultimine should be able to mark the excavate area as well.

**Minecraft Enviorment**
 - Minecraft Version: 1.16.5
 - XRay Mod Version: 2.7.0
 - Mod Pack & Version if applicable: Enigmatica 6 0.5.4
 - Forge Version if applicable: 36.1.31

**Comment by MichaelHillcox** [comment]
Sounds like a render leak, I'll look into this, thanks

**Comment by GoliathX211** [comment]
This mod as many of these instances. I never found it that intrusive and just toggled it off momentarily. The mod stops the render with the creative worldshaper from Create as well.

**Comment by MichaelHillcox** [comment]
This should be fixed in newer versions :D
