### ISSUE TITLE
Obsidian crashes the game

### ISSUE THREAD

**Issue by AchievedZeus574** [AdvancedXRay/XRay-Mod#192]
**Describe the bug**
When adding Obsidian (ID 49), the game saves and closes.

**To Reproduce**
1. Have a modpack with any amount of mods in it
2. Open the Xray menu
3. Add block ID 49 

**Expected behavior**
I was expecting the mod to add it without issue like it had with any other block so far.

**Minecraft Enviorment**
 - Minecraft Version: 1.7.10
 - XRay Mod Version: fgtXray-1.7.10-1.0.1.75 (not sure where to find it, that's just the file name)
 - Mod Pack & Version if applicable: Any modpack running 1.7.10
 - Forge Version: 10.13.4.1614

**Additional context**
Doubt this was part of the issue, but each time I added it I called it "Obsidian" spelled like tha
[crash-2022-01-08_16.24.29-client.txt](https://github.com/MichaelHillcox/XRay-Mod/files/7834129/crash-2022-01-08_16.24.29-client.txt)
t

**Comment by AchievedZeus574** [comment]
Wanted to leave an update:
It seems to crash with any vanilla block, but modded blocks are fine. Only happens when adding the block, but not when using the pre added ones.

**Comment by MichaelHillcox** [comment]
1.7.10 is no longer supported. PR's are welcome.
