### ISSUE TITLE
MineCraft Freeze Bug

### ISSUE THREAD

**Issue by Binners4019** [AdvancedXRay/XRay-Mod#194]
Sometimes when i press the button to bring up the menu to enable and disable blocks to be viewed. The game will freeze and will do so until the game is restarted.
I have no issues with toggling the xray on and of, however every 1 in 3 chance the game can freeze with the menu.
it maybe a bug freeze when having an activated block or when pressed to fast.

**Minecraft Enviorment**
 - Minecraft Version: 1.16.5
 - XRay Mod Version: advanced-xray-forge-1.16.5-2.7.0.jar
 - Mod Pack & Version if applicable: Only Mod
 - Forge Version: 36.2.20

**Additional context**
Have a good day :)
i love your mod as it makes mining much more enjoyable and the amount of time mining is reduced allowing me time to build houses and that.

**Comment by Haitam54** [comment]
i'm actually having the same issue and it sometimes just works and other times freezes idk why

**Comment by MichaelHillcox** [comment]
Lower your distance. This is due to poor optimisations in 1.16 but I won't be going back to fix it as I don't support that MC version anymore. PR's are welcome.
