### ISSUE TITLE
Not Working With Sildurs Enhanced Defualt and Potentionally other shaders

### ISSUE THREAD

**Issue by FlamingOni** [AdvancedXRay/XRay-Mod#197]
Like the title says, for some reason when I have shaders activated and this mod on and running, the outlines don't ever show up

**Comment by randomairborne** [comment]
Shaders and OptiFine are not supported, you can read about why on the CurseForge page.

**Comment by FlamingOni** [comment]
That's weird cause it has been Optifine and this mod has been working perfectly fine for me in 1.16-1.18. Its only when I added a shader that it stopped working

**Comment by randomairborne** [comment]
It's specifically shaders that cause the issue, but optifine in general is closed source and Mikey has not wanted to deal with the pain that is OptiFine bugfixing
