### ISSUE TITLE
ESP for heads doesn't show in certain situations

### ISSUE THREAD

**Issue by Destroyer0201** [AdvancedXRay/XRay-Mod#201]
**Describe the bug**
A head that is placed on to the wall: on the side of a block, wont show. While normal player heads that are on top of a block shows

**To Reproduce**
1. Place a player head on the side of a block and use ESP

**Expected behavior**
ESP should work for player heads on walls as well

**Minecraft Enviorment**
 - Minecraft Version: [eg: 1.182]
 - XRay Mod Version: [eg: 2.11.0 Build 7]

**Comment by MichaelHillcox** [comment]
IIRC, heads are NBT based and I don't search for NBT. This might be a nice feature in the future but right now, due to the way the scanning is written, it would put a dramatic amount of strain on a users' system.

**Comment by MichaelHillcox** [comment]
Closed in preference of #179
