### ISSUE TITLE
Adding "Legit Mode" Option to only show visible/exposed items.

### ISSUE THREAD

**Issue by InsightiousCoven** [AdvancedXRay/XRay-Mod#202]
**Is your feature request related to a problem? Please describe.**
Because anti-xray nowadays, it will break the mod xray 

**Describe the solution you'd like**
an option to choose whether show all items, or only visible items.
Something like Legit Mode option.

It will allow seeing items in the condition they are visible,
so the mod only highlights visible / exposed items:
[from inside](https://snipboard.io/IgrMVF.jpg)
[from outside](https://snipboard.io/Gw8zH4.jpg)

**Describe alternatives you've considered**
Right now I'm using Xray from Aristois client, 
but I love and prefer how AdvancedXray mod HUD with highlight, 
instead of xray mod that hides not wanted items (making them invisible).

This is the main reason I propose this request,

**Additional context**
I think I already explain so much on the above.

**Comment by MichaelHillcox** [comment]
The performance impact of computing visible blocks to your player would be mad. Sure, it's possible, but just don't use it on servers that don't want you to. It's not that hard.
