### ISSUE TITLE
Unable to disable and enable blocks in the gui

### ISSUE THREAD

**Issue by 1ceBergus** [AdvancedXRay/XRay-Mod#204]
**Describe the bug**
Everything works perfectly fine up until I open the gui to disable and enable blocks of which it simply wont allow me to do. The only way I can enable blocks is to add them from hand of which they'll automatically be enabled.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Minecraft Enviorment**
 - Minecraft Version: [1.12.2]
 - XRay Mod Version: [1.6.0]
 - MC Eternal 1.3.8 LITE
 - Forge 14.23.5.2854

**Additional context**
I've had no issues with the mod in the past

**Comment by lightman210567** [comment]
I am also having this issue in 1.12.2 with mod version 1.6.0

**Comment by NinaRuiz** [comment]
Having the same issue, here 😅

**Comment by MichaelHillcox** [comment]
1.12 is no longer supported
