### ISSUE TITLE
Blocks not being highlighted

### ISSUE THREAD

**Issue by dorktripp** [AdvancedXRay/XRay-Mod#208]
**Describe the bug**
When toggling the x-ray, enabled blocks are not being highlighted.

**To Reproduce**
1. Toggle default x-ray button in game.

**Expected behavior**
For the x-ray feature to activate.

**Minecraft Environment**
 - Minecraft Version: 1.19
 - X-Ray Mod Version: 1.19-2.12.2-build.14
 - Forge Version: 1.19-41.0.98

**Additional context**
The x-ray feature was working before adding the key binding element, in one of the previous build versions. I noticed the x-ray stopped working in build.13, then I updated to build.14, with no changes.

**Comment by MichaelHillcox** [comment]
Works I'm my dev env so I'd assume you're using shaders or optifine? Could be other mods causing the issues, can you share a list of mods you're using?

**Comment by dorktripp** [comment]
Yes, i'm still new to minecraft.

The mods list goes as follows:

- Advanced Netherite
- Biomes-O-Plenty
- Corpse
- Just Enough Items
- Oculus
- Rubidium
- Sky Villages (freshly installed)
- Terra Blender
- Terralith
- Xaero's Minimap

any help would be greatly appreciated :)

**Comment by dorktripp** [comment]
After testing my mods, rubidium is the reason why the xray wasn't working properly.
