### ISSUE TITLE
Cannot add a modded block into the xray list

### ISSUE THREAD

**Issue by adamschmiff** [AdvancedXRay/XRay-Mod#210]
**Describe the bug**
Cannot add a modded block into the xray list

**To Reproduce**
1. step one: try and add a modded block
2. get error message

**Expected behavior**
Thought by typing the mod id and block id into the add block section of the xray menu it would add a custom block

![image](https://user-images.githubusercontent.com/68395290/181368721-7d87fd93-3cc4-48b4-8586-32161005a247.png)

**Minecraft Enviorment**
 - Minecraft Version: 1.7.10
 - XRay Mod Version: 1.0.1.75

**Comment by MichaelHillcox** [comment]
For really old versions of MC, you have to use just the id of the block, this is intended.
