### ISSUE TITLE
Add option to make blocks transparent

### ISSUE THREAD

**Issue by LuckyMika** [AdvancedXRay/XRay-Mod#211]
**Is your feature request related to a problem? Please describe.**
It's really hard for my eyes to look at all the blocks rendered.

**Describe the solution you'd like**
Add an option to make blocks transparent.

**Describe alternatives you've considered**
Another option would be to fade opacity of the block outlines with distance.

**Additional context**
https://www.nhs.uk/conditions/eye-cancer/

**Comment by MichaelHillcox** [comment]
Turn down the distance. You don't need a high distance.
