### ISSUE TITLE
all wireframes are white

### ISSUE THREAD

**Issue by jcdeepdigger** [AdvancedXRay/XRay-Mod#215]
**Describe the bug**
im using [Advanced XRay // MC1.12.2 - 1.6.0] and playing on Clockwerks Pixelmon 1.12.2 and all the "wireframes" are white even though i picked diffrent colors

**To Reproduce**
1. step one

**Expected behavior**
Different colored frames for what i picked

**Screenshots**
If applicable (delete if not), add screenshots to help explain your problem.

**Minecraft Enviorment**
 - Minecraft Version: [eg: 1.12.2] = 1.12.2
 - XRay Mod Version: [eg: 1.5.0] = 1.6.0

 - Mod Pack & Version if applicable: Clockwerks Pixelmon 1.12.2
 - Forge Version if applicable: Forge - 14.23.5.2860

**Additional context**
![whiteframes](https://user-images.githubusercontent.com/116136417/196589847-511d1dbe-1cb4-4034-a736-a86ce0fb0a7d.jpg)

**Comment by MichaelHillcox** [comment]
This is an old one, and I don't support 1.12 any more... But I think it's the journey map that can cause the issue.
