### ISSUE TITLE
How can i attach it as a resource pack?

### ISSUE THREAD

**Issue by LonelySwordsman** [AdvancedXRay/XRay-Mod#224]
**Is your feature request related to a problem? Please describe.**
I am new to this and I have no idea how to make it a resource pack itself. I do have java installed on my computer.

**Describe the solution you'd like**
I would like to have a tutorial on how to do this.

**Describe alternatives you've considered**
Maybe someone can give me a step by step.

**Comment by MichaelHillcox** [comment]
It's not a resource pack. It's a mod. Google how to use forge mods.
