### ISSUE TITLE
Unable to locate keybinds for the Xray

### ISSUE THREAD

**Issue by LonelySwordsman** [AdvancedXRay/XRay-Mod#225]
**Describe the bug**
The keybinds for the xray cannot be found in settings. (at least in my case)

Ability to create the bug again is unknown

**Expected behavior**
What I expected to happen was to find the keybinds, but unfortunately wasn't able to locate them.

**Minecraft Enviorment**
 - Minecraft Version: 1.19.3
 - XRay Mod Version: 1.19.3-1.3.0-build
 - 1.19.3-forge-44.1.8
![2023-02-02_18 26 35](https://user-images.githubusercontent.com/124238728/216498539-65e4033a-cf93-4e53-bbec-7f49b51ca587.png)

**Comment by LonelySwordsman** [comment]
I dont know if there even is a keybind setting for it

**Comment by MichaelHillcox** [comment]
You've installed the fabric version of the mod. Not the forge one.
