### ISSUE TITLE
I think is a BUG but I can't change color, edit or delete objects

### ISSUE THREAD

**Issue by Dacreth** [AdvancedXRay/XRay-Mod#227]
When I try to save an object, for example Gold Ore, I can't change colors, there's just a bar with colors from blue to pink.

here the image: 
![image1](https://user-images.githubusercontent.com/126122157/220787187-f655c4f6-9532-414a-a379-bb8ab084d6d2.png)

**Comment by MichaelHillcox** [comment]
Looks like you have a mod breaking GUIs.
