### ISSUE TITLE
XRay not updating highlights automaticly while active

### ISSUE THREAD

**Issue by Snablorangen** [AdvancedXRay/XRay-Mod#228]
**Describe the bug**
Im running the 1.18.2 Forge version of the mod. I've added a few modded blocks that I would like to see, and when they're outlined through other blocks as expected. However, when broken, the outline is still rendered even though the block is broken. I need to press the xray button twice to disable and reenable the xray for it to update.

**To Reproduce**
1. Enable xray
2. Break a block that is highlighted while using xray
3. disable and enable the xray for the highlighting to update correctly

**Expected behavior**
I would want the highlight to be removed when the block is broken. I think there should be some kind of update when a highlighted block is broken, or just on an interval of some kind.

**Minecraft Enviorment**
 - Minecraft Version: 1.18.2 Forge
 - XRay Mod Version: 2.11.0-build.7
 - Mod Pack & Version: Vault Hunters 3rd Ed - Update 7H
 - Forge Version: --

**Comment by MichaelHillcox** [comment]
This should be fixed in newer, supported, versions of the mod
