### ISSUE TITLE
wont work with shaders

### ISSUE THREAD

**Issue by TheCraftedGamer** [AdvancedXRay/XRay-Mod#232]
cant find a way to make the mod overwrite shaders. only works when shaders are off.

**Comment by MichaelHillcox** [comment]
If only there was a pinned issue explaining this #132 and a whole second in the curseforge page dedicated to it as well.

**Comment by TheCraftedGamer** [comment]
> If only there was a pinned issue explaining this #132 and a whole second in the curseforge page dedicated to it as well.

ok, no one reads pins cause either no one knows it's there or there are too many to find my issue. in my case, I didn't know it was there and also never bother trying to find my issue. also no where on the Curseforge page does it say that x-ray doesn't work with **"SHADERS"**. unless you are trying to refer to the text that states and I quote "A note on Optifine Currently, the mod does not and has not work with Optifine since MC 1.7.x. I am not sure why the two mods do not work together and due to Optfine being closed source I don't have the ability to investigate it properly. For now, I just recommend not using the two mods together. I hope to have it fixed soon." however, x-ray works perfectly fine with 1.19.3 optifine until I add a shader/turn it on.
so please hold off on the sarcasm for later. this is a place where we resolve conflicts not spit fire at each other.
