### ISSUE TITLE
Application Crash - Minecraft 1.19.4 With Forge & Fabric

### ISSUE THREAD

**Issue by AnomicFlux** [AdvancedXRay/XRay-Mod#233]
**Describe the bug**

Mod feature causes a game crash quickly after opening any custom GUI related to the mod.

**To Reproduce**
1. Open Minecraft application
2. Using Forge OR Fabric (crashes on both)
3. Enter a game save
4. Press G to open the mod's menu
5. Application will crash

**Expected behavior**
Expected GUI's in question to open without critical errors.

**Screenshots:**

![image](https://user-images.githubusercontent.com/81651978/227653694-68f5a2b3-99d9-4992-8dc7-3dcf7e36945b.png)

**Minecraft Environment**
 - Minecraft Version: 1.19.4
 - XRay Mod Version: 2.14.0-build.16
 - Forge Version : 45.0.24 (1.19.4)

**Additional context**

[crash-2023-03-24_15.17.32-client.txt](https://github.com/AdvancedXRay/XRay-Mod/files/11066905/crash-2023-03-24_15.17.32-client.txt)

**Comment by MichaelHillcox** [comment]
It's not ported yet
