### ISSUE TITLE
Not highlighting the ores I'm looking for, just random block.

### ISSUE THREAD

**Issue by ZanJosiah** [AdvancedXRay/XRay-Mod#237]
**Describe the bug**

**To Reproduce**
1. step one

**Expected behavior**

**Screenshots**
If applicable (delete if not), add screenshots to help explain your problem.

**Minecraft Enviorment**
 - Minecraft Version: [eg: 1.12.2]
 - XRay Mod Version: [eg: 1.5.0]
 - Mod Pack & Version if applicable
 - Forge Version if applicable

**Additional context**

**Comment by ZanJosiah** [comment]
I've used the Advanced Xray mod on another server and it worked fine, but when playing on that same custom forge profile but adding another server to it, it doesn't work there. If I try to search for iron or diamonds etc etc... it just highlights random blocks that aren't even ores. The only ore that works correctly is coal. I seen that it's not compatible with optifine so I uninstalled it hoping it would be the answer to the problem, but no it's still happening and I can't think of any other reason it would be doing this. I will update this with screenshots soon. I'm also using 1.19.4

**Comment by ZanJosiah** [comment]
I've used the Advanced Xray mod on another server and it worked fine, but when playing on that same custom forge profile but adding another server to it, it doesn't work there. If I try to search for iron or diamonds etc etc... it just highlights random blocks that aren't even ores. The only ore that works correctly is coal. I seen that it's not compatible with optifine so I uninstalled it hoping it would be the answer to the problem, but no it's still happening and I can't think of any other reason it would be doing this. I will update this with screenshots soon. I'm also using 1.19.4

**Comment by SunPodder** [comment]
Same issue here. It did work on the same server before though. Maybe the server is using some kind of anti-xray mods?
![Screenshot from 2023-10-21 11-23-15](https://github.com/AdvancedXRay/XRay-Mod/assets/73415680/8f39a968-1d0f-465b-8d4b-b080863ac93a)

**Comment by MichaelHillcox** [comment]
Don't use the mod on servers that don't want you too
