### ISSUE TITLE
Discord: Is it gone?

### ISSUE THREAD

**Issue by LunarAnticGitHub** [AdvancedXRay/XRay-Mod#238]
**Describe the bug**
This is LunarAntic from Discord, the channel for Advanced X-rays development has gone missing and the link on the Forge page goes nowhere, did it get deleted?

**To Reproduce**
1. Go to https://www.curseforge.com/minecraft/mc-mods/advanced-xray
2. Click on Discord link in mod description 

**Expected behavior**
No Discord come up when I hit the link
![Screenshot_20230425-160749](https://user-images.githubusercontent.com/131813123/234391090-da208ef0-56f5-4425-b834-1967b3f13d33.png)
![Screenshot_20230425-160744](https://user-images.githubusercontent.com/131813123/234391117-46c82ea3-b0bd-402b-b9b2-09b3db8977a6.png)

**Comment by MichaelHillcox** [comment]
Yeah, I closed it, too many people asking how to open the gui even though it's in the readme.
