### ISSUE TITLE
Почему теперь автоматически не показывает все руды?

### ISSUE THREAD

**Issue by pandamonkeez** [AdvancedXRay/XRay-Mod#243]
In older versions of the mod, all ores were immediately added. But for some reason, in new versions, you have to manually set all the ores. Please fix this or add config.

**Comment by pandamonkeez** [comment]
I play on fabric and with installed sodium

**Comment by MichaelHillcox** [comment]
Sometimes ores fail to add, you can try and delete your config and see if this fixes it but it's typically not worth it
