### ISSUE TITLE
Discord links STILL do not work, am I banned or something 

### ISSUE THREAD

**Issue by LunarAnticGitHub** [AdvancedXRay/XRay-Mod#245]
**Describe the bug**
The link that was emailed to me said it was expired, if I am banned I demand to know the terms

![Screenshot_20230607-140239](https://github.com/AdvancedXRay/XRay-Mod/assets/131813123/26c0be78-7bce-479a-9ca8-fed29ea48d37)

https://discord.gg/KV7yDTfEkm does not get me in

**Comment by MichaelHillcox** [comment]
What's your discord name?

**Comment by LunarAnticGitHub** [comment]
LunarAntic#1912
