### ISSUE TITLE
Bring it to Minecraft 1.20 Forge

### ISSUE THREAD

**Issue by YashjitPal** [AdvancedXRay/XRay-Mod#246]
As you have noticed that Forge 1.20 is released and it's been a while for us to wait for 1.20 and so I immediately turned my world to 1.20 but this mod is limited to 1.20, so can you please update the mod to 1.20 forge afap?

**Comment by MichaelHillcox** [comment]
Go away

**I will port it when I have time. As all modders that wish to continue to support their mods will do. Please be patient and allow modders time to port their mods. You don't need to make an issue...**
