### ISSUE TITLE
1.20 support?

### ISSUE THREAD

**Issue by YashjitPal** [AdvancedXRay/XRay-Mod#247]
Please just update the mod to 1.20

**Comment by GamlinUK** [comment]
https://github.com/AdvancedXRay/XRay-Mod/issues/246

> I will port it when I have time. As all modders that wish to continue to support their mods will do. Please be patient and allow modders time to port their mods. You don't need to make an issue...

**Comment by GamlinUK** [comment]
Wait that's you - like dude said just wait, Michael does this in their own time :)

**Comment by Gaz492** [comment]
When port?

**Comment by 5ully** [comment]
@YashjitPal  When are you porting it?
