### ISSUE TITLE
Player heads with a skin dont show us

### ISSUE THREAD

**Issue by Honeybee7447** [AdvancedXRay/XRay-Mod#248]
**Describe the bug**

Player heads that have a skin dont show when scanning for player heads

**To Reproduce**
1. make a player head with a skin
2. place it and turn on the xray to look for it and it doesnt show

**Expected behavior**

to see all player heads regardless if they have a skin on them or not

**Screenshots**
If applicable (delete if not), add screenshots to help explain your problem.

**Minecraft Enviorment**
 - Minecraft Version: 1.20.1
 - XRay Mod Version: advanced-xray-forge-1.20.1-2.17.0-build.20
 - Mod Pack & Version if applicable
 - Forge Version if applicable- forge-1.20.1-47.0.3-installer

**Additional context**

**Comment by MichaelHillcox** [comment]
Yeah, this is because it uses nbt and not state. I'm unlikely to implement this.

**Comment by MichaelHillcox** [comment]
I'm curious on the usecase?

**Comment by MichaelHillcox** [comment]
I'm guessing this server wouldn't be happy with you cheating their mini games

**Comment by MichaelHillcox** [comment]
Closing in preference of #179
