### ISSUE TITLE
Cannot toggle blocks on or off

### ISSUE THREAD

**Issue by TinyDeskEngineer06** [AdvancedXRay/XRay-Mod#250]
**Describe the bug**
I've been experiencing an issue with the latest 1.12.2 version of the mod (xray-1.12.2-1.6.0), with me being incapable of disabling/enabling block entries with this mod. I've tried all the mouse buttons, as well as every single key on the keyboard, but nothing I've tried so far appears to have any effect.

**To Reproduce**
1. Open configuration menu
2. Attempt to toggle entry

**Expected behavior**
It be possible to toggle block entries on or off.

**Minecraft Enviroment**
 - Minecraft Version: 1.12.2
 - XRay Mod Version: 1.6.0
 - No additional mods at all
 - Forge version 14.23.5.2859

**Comment by GAMINGCHATS** [comment]
Same thing for me too!

**Comment by GAMINGCHATS** [comment]
@TinyDeskEngineer06 It's shift+left-click. 🤦  **@MichaelHillcox add it to the Read me!**

**Comment by MichaelHillcox** [comment]
1.12 is no longer supported
