### ISSUE TITLE
The editing window appears for a second and closes

### ISSUE THREAD

**Issue by UrbanSide** [AdvancedXRay/XRay-Mod#253]
**Describe the bug**
The editing window appears for a second and closes

**To Reproduce**
1. Shift+right mouse button

**Expected behavior**

**Screenshots**
If applicable (delete if not), add screenshots to help explain your problem.

**Minecraft Enviorment**
 - Minecraft Version: 1.18.2
 - XRay Mod Version: last
 - Mod Pack & Version if applicable: OxFORTPACK 8.4
 - Forge Version if applicable: last

**Comment by MichaelHillcox** [comment]
I wouldn't recommend binding the key to a mouse key, this is known to cause issues with Minecraft
