### ISSUE TITLE
Crash On Launch

### ISSUE THREAD

**Issue by LVdashndbfaigbad** [AdvancedXRay/XRay-Mod#256]
**Describe the bug**
Crashes on launch with exit-code 1

**To Reproduce**
1. Launch the mod through forge, (this should open up a minecraft launcher)
2. Launch the installation
3. It crashes

**Expected behavior**
I expected it to launch the modded minecraft client.

**Minecraft Enviorment**
 - Minecraft Version: 1.20.1
 - XRay Mod Version: 2.17
 - Forge Version: 47.2.0

**Comment by MichaelHillcox** [comment]
Please attach a crashlog

**Comment by superdusto** [comment]
I am having the same issue.
[launcher_log6.txt](https://github.com/AdvancedXRay/XRay-Mod/files/13447205/launcher_log6.txt)

**Comment by MichaelHillcox** [comment]
My mod is not in the log you posted. Also, no response from the original author so closing.
