### ISSUE TITLE
Will we ever get a 1.20.2 version or are you done with developing this mod? I would understand if you're done, you've made so many versions of it at this point

### ISSUE THREAD

**Issue by DoktorVem** [AdvancedXRay/XRay-Mod#257]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MichaelHillcox** [comment]
Yes

**Comment by MichaelHillcox** [comment]
Shipped
