### ISSUE TITLE
[1.19.3] Xray not working anymore after using it in a server

### ISSUE THREAD

**Issue by RejectMonke** [AdvancedXRay/XRay-Mod#258]
**Describe the bug**
I've joined a server while using this xray mod (just for experiment) which xray is useless there and im not using it to cheat, but when I activated it it didn't work, I thought it was just a little anti xray but then I joined my own minecraft world and now the xray didnt work anymore at all

**To Reproduce**
1. Join luckynetwork.net server
2. activate the xray
3. enter an offline minecraft world and activate the xray 

**Expected behavior**
The xray will not work anymore it will only lag the game

**Minecraft Enviorment**
 - Minecraft Version: 1.19.3
 - XRay Mod Version: 2.14.0

**Comment by MichaelHillcox** [comment]
I don't support using the mods on servers.
