### ISSUE TITLE
[Unplayable] Can not toggle the Mod.

### ISSUE THREAD

**Issue by YamiNoKanata** [AdvancedXRay/XRay-Mod#262]
**Describe the bug:**
I Assigned the two Buttons. 
- I can Open the GUI to Add Blocks.
- I can not toggle the X-Ray. 
    - If i tab the Button, it do nothing,

---

**Minecraft Enviorment:**
 - Minecraft Version: 1.7.10
 - XRay Mod Version: 1.0.8
 - Mod Pack: Greg Tech: New Horizons

**Comment by AstroTuber** [comment]
try removing optifine

**Comment by MichaelHillcox** [comment]
1.7.10 is not supported any more. Last I checked, it did still work
