### ISSUE TITLE
Error loading mods

### ISSUE THREAD

**Issue by hochmuss** [AdvancedXRay/XRay-Mod#263]
**Describe the bug**
![image](https://github.com/AdvancedXRay/XRay-Mod/assets/160625159/b3abe703-2330-4f7c-96a8-7629006896fb)

**To Reproduce**

1. copy the mod in the mod folder
2. start minecraft

**Expected behavior**

It should load the mod without errors

**Minecraft Enviorment**

 - Minecraft Version: [1.20.4]
 - XRay Mod Version: [84.0.0]
 - Mod Pack & Version: [Advanced-XRay-Mod-NeoForge-1.20.4]
 - Forge Version: [Neoforge 20.4.161-beta]

**Additional context**

[crash-2024-02-20_16.31.13-fml.txt](https://github.com/AdvancedXRay/XRay-Mod/files/14347712/crash-2024-02-20_16.31.13-fml.txt)

**Comment by Er39** [comment]
Me too, exactly the same

Enviorment
- Minecraft: [1.20.4]
- NeoForge: [20.4.196]
- XRay-Mod: [84.0.0]

Use mod: Only xray

**Comment by risssv** [comment]
Same problem for me too.

**Comment by Ingonduran** [comment]
Same to me.

Minecraft Enviorment
    Minecraft Version: [1.20.4]
    XRay Mod Version: [84.0.0]
    Forge Version: [Neoforge 20.4.232]

[latest.log](https://github.com/AdvancedXRay/XRay-Mod/files/15435945/latest.log)
[crash-2024-05-24_10.31.04-fml.txt](https://github.com/AdvancedXRay/XRay-Mod/files/15435956/crash-2024-05-24_10.31.04-fml.txt)

**Comment by MichaelHillcox** [comment]
Hmm, interesting, they must have changed their api in later versions, I'll see if I can push an update for this in a few

**Comment by MichaelHillcox** [comment]
Should be fixed once this pipeline finishes https://github.com/AdvancedXRay/XRay-Mod/actions/runs/9271493391/job/25507002744
