### ISSUE TITLE
Shriekers cannot be detected

### ISSUE THREAD

**Issue by PyroGabrielKotzell** [AdvancedXRay/XRay-Mod#264]
**Describe the bug**
The sculk shriekers naturally spawning in the ancient cities are not detected by the mod.

**To Reproduce**
1. Add the shrieker to the list of blocks and enable it.
2. Go near a shrieker with xray on.

**Expected behavior**
The shrieker should have an outline of the desired color. But it will not.

**Screenshots**
![image](https://github.com/AdvancedXRay/XRay-Mod/assets/116422802/210ed6cd-6a08-4346-9983-4bc8f0f757e2)
![image](https://github.com/AdvancedXRay/XRay-Mod/assets/116422802/c0760f6c-4c35-4379-9a8d-26a898e4b663)

**Minecraft Enviorment**
 - Minecraft Version: 1.19.4
 - XRay Mod Version: 1.4.0-build 15

**Additional context**
Kind of explicative by itself

**Comment by MichaelHillcox** [comment]
Closed in preference of #179
