### ISSUE TITLE
issue adding ores

### ISSUE THREAD

**Issue by i9xgit** [AdvancedXRay/XRay-Mod#265]
**Describe the bug**
when attempting to add ores from gregtech it just simply does not add the ores

**To Reproduce**
1. step one: attempt to add gtceu:netherrack_emerald_ore
2. pick color click add
3. done

**Expected behavior**
1. step one: attempt to add gteuc:netherrack_emerald_ore
2. pick color click add
3, be able to xray the ore 

**Screenshots**
If applicable (delete if not), add screenshots to help explain your problem.

**Minecraft Enviorment**
 - Minecraft Version: [eg: 1.12.2] 1.20.1
 - XRay Mod Version: [eg: 1.5.0]  advanced-xray-forge-1.20.1-2.18.1-build.22.jar
 - Mod Pack & Version if applicable 0.25.6 all the mods 9
 - Forge Version if applicable not sure

**Additional context**

**Comment by i9xgit** [comment]
https://youtu.be/0VJ6yco1J1s video of issue

**Comment by MichaelHillcox** [comment]
Looks like the video is gone... I'm not sure what would be causing...

**Comment by UfaiX04** [comment]
I'm encountering the same error with GregTech new horizon in 1.7.10. Adding the blocks with tag:meta does not work
One weird thing is that by adding a tag:meta block tag without the name crashed the game. After joining back in the world the xray worked.
![Screenshot 2024-06-12 153210](https://github.com/AdvancedXRay/XRay-Mod/assets/64732224/33fc423d-9329-4010-907e-065756649625)
![Screenshot 2024-06-12 153210](https://github.com/AdvancedXRay/XRay-Mod/assets/64732224/33fc423d-9329-4010-907e-065756649625)

**Comment by VasylMartyniv** [comment]
Same issue here

**Comment by MichaelHillcox** [comment]
1.7.10 is not supported anymore. Although just deleting the config should fix it
