### ISSUE TITLE
[Unplayable] Toggling but not showing blocks.

### ISSUE THREAD

**Issue by Storm1322** [AdvancedXRay/XRay-Mod#266]
**Describe the bug:**

Block outlines don't show up after toggling the xray. I assigned the buttons UI to add blocks shows up and can add and enable/disable blocks. I tried deleting optifine and disabling all resource packs to no avail. Not using any shaders.

**Minecraft Enviorment:**

 - Minecraft Version: 1.12.2
 - XRay Mod Version: 1.6.0
 - Mod Pack: Rebirth of the Night / Version: 3.2.1b
 - Forge Version: 14.23.5.2860

**Comment by MichaelHillcox** [comment]
1.12 is no longer supported but I can confirm this mod was working last I checked on 1.12. It may be that one of your mods is causing issues
