### ISSUE TITLE
played scary music disc

### ISSUE THREAD

**Issue by octuaOSdev** [AdvancedXRay/XRay-Mod#268]
so i installed the mod in 1.12.2
and when i launched a world it started playing a music disc
at first i thought it was cave sounds 
_THEN i realised that i turned them off_
soooooooooooooooooooooooooooooooooooooooooooooooo
and i turned music discs off and **it still played**
i got scared and turned off the world and minecraft instance
i dont have the instance anymore since i switched PC since then _yes i know its weird to be making an issue about this so late_ but im finally tring to figure out why that disc played and btw it didn´t say that _now playing:_ text
anyways i hope SOMEBODY KNOW WHAT IM TALKING ABOUT

**Comment by MichaelHillcox** [comment]
This is nothing to do with my mod.

**Comment by octuaOSdev** [comment]
hmm it never played without this mod soo idk if its just another mod that plays that disc if an xray mod is installed wich isnt impossible sooo
