### ISSUE TITLE
Cannot switch xray for each ore

### ISSUE THREAD

**Issue by HAlThO** [AdvancedXRay/XRay-Mod#271]
**Describe the bug**
Cannot switch xray for each ore.

**To Reproduce**
1. Open xray menu
2. Click on the enabled or disabled ore

**Expected behavior**
xray cannot be enabled or disabled

**Minecraft Enviorment**
 - Minecraft Version: [eg: 1.12.2]
 - XRay Mod Version: [eg: 1.6.0]

**Additional context**
It worked fine in version 1.5.0

**Comment by MichaelHillcox** [comment]
What mc version?

**Comment by HAlThO** [comment]
forge 1.12.2-14.23.5.2860

**Comment by MichaelHillcox** [comment]
Last I checked this version still works but I don't support 1.12 any more. You might have to shift click or something
