### ISSUE TITLE
"Error loading class: java/lang/Boolean (java.lang.IllegalArgumentException: Unsupported class file major version 66)" when using Java 22

### ISSUE THREAD

**Issue by Heraclius** [AdvancedXRay/XRay-Mod#272]
**Describe the bug**
Attempting to load the latest version of the mod (for MC 1.20.6) using Java 22 crashes the game upon startup. Switching to Java 21 fixes the issue.

**To Reproduce**
1. Set up Minecraft 1.20.6
2. Install NeoForge 20.6.116
3. Install Advanced XRay 86.0.0 
4. Launch the game using Java 22
5. It doesn't launch!

**Expected behavior**
I expect the game to launch?

**Minecraft Enviorment**
 - Minecraft Version: 1.20.6
 - XRay Mod Version: 86.0.0
 - NeoForge 20.6.116

**Additional context**
For context, this is on Windows 10. Here is the full MultiMC log file: [log.txt](https://github.com/user-attachments/files/15825180/log.txt)

**Comment by MichaelHillcox** [comment]
Minecraft doesn't use java 22
