### ISSUE TITLE
All thermal foundation ore counts as one ore

### ISSUE THREAD

**Issue by qZaaakk** [AdvancedXRay/XRay-Mod#283]
**Describe the bug**

1. When am trying to xray for thermal foundation ores they all counts as one ore. For example if I want to xray for copper ore (thermal foundation) its going to xray every other thermal foundation ore like tin and etc. Am not sure if it shows every other thermal foundation ore but it shows other ores too.
2. When am in the xray menu and if I already have an thermal foundation ore in it I cannot add other thermal foundation ores. For example if I added lead ore (thermal foundation) I will not be able to add any other thermal foundation ores just like if I want to add iron ore (vannila) whilst its already in the menu.

**Minecraft Enviorment**
 - Minecraft Version: 1.12.2
 - XRay Mod Version: xray-1.12.2-1.6.0.jar
 - Mod Pack: Enigmatica 2: Expert - Extended, v1.43.0
 - Forge Version: forge-14.23.5.2860

**Comment by MichaelHillcox** [comment]
I don't support 1.12 any more... IIRC, holding it in your hand and adding it via the add from hand button might fix it
