### ISSUE TITLE
1.21-1.21.1 for Forge, not Neoforge

### ISSUE THREAD

**Issue by raccoonzez** [AdvancedXRay/XRay-Mod#284]
**Describe the solution you'd like**
I already technically already asked this but I didn't get a concise answer. Will AdvancedXray be updated to forge 1.21?

**Comment by MichaelHillcox** [comment]
See other reply

**Comment by raccoonzez** [comment]
I understand but the response in the other reply makes no sense, you say the mod is out for forge 1.21 but its not, its only out for neoforge

**Comment by MichaelHillcox** [comment]
Sorry, yes, to confirm, the mod is out for neoforge and fabric for 1.21. I do not currently have any specific plans to support forge again as their api's seem to always be half done or missing. A couple of the required things I need for this mod simply do not exist
