### ISSUE TITLE
It does not allow me to see all the existing blocks of the version

### ISSUE THREAD

**Issue by yisusprain** [AdvancedXRay/XRay-Mod#292]
**Describe the bug**
It does not allow me to see all the existing blocks of the version

**Expected behavior**
It does not allow me to see all the existing blocks of the version, only some, I don't know if blocks can be added manually, but what I could do was add more, touching things without knowing, but there are still many more blocks to mark and unmark, and I don't know what to do, I want to see chests, spawners, mineral blocks, but they don't come out, I previously used this in version 1.8 years ago, and something like this had never happened to me, it doesn't work for me in 1.19.2, or 1.19.3,

**Screenshots**
![image](https://github.com/user-attachments/assets/198aaebc-f867-4d8f-8ca0-9829f5da2a07)

**Minecraft Enviorment**
 - Minecraft Version: [eg: 1.19.2]
 - XRay Mod Version: [v74-1192]

**Additional context**

**Comment by MichaelHillcox** [comment]
Not my mod.
