### ISSUE TITLE
Crash while playing ATM10

### ISSUE THREAD

**Issue by SamHammie** [AdvancedXRay/XRay-Mod#294]
**Describe the bug**
While playing All The Mods 10, trying to search for a block to add garners a full game crash.

**To Reproduce**
1. Be playing ATM10
2. Search for a block to add
3. Crash

**Expected behavior**
After step 2, don't crash

**Minecraft Enviorment**
 - Minecraft Version: 1.21.1
 - XRay Mod Version: 21.0.0
 - Mod Pack & Version if applicable: ATM10 versions 2.3 and 2.2
 - Forge Version if applicable: NeoForge 21.1.89

**Additional context**
Logs: https://mclo.gs/EPlnJcO

**Comment by roflnomish** [comment]
same issue here. worked fine on ATM10 version 10-2.0 and 2.1, but after updating i get a crash when trying to search for blocks. blocks i already have in the list work fine, but i can't add any more :(

[latest.log](https://github.com/user-attachments/files/18133053/latest.log)

**Comment by SamHammie** [comment]
> same issue here. worked fine on ATM10 version 10-2.0 and 2.1, but after updating i get a crash when trying to search for blocks. blocks i already have in the list work fine, but i can't add any more :(
> 
> edit: you can still add stuff to your list via the 'add looking at' button, but you obvs need to have found and be looking at the block first. at least its still possible!
> 
> crash log: https://mclo.gs/3SBAUQR

Not an ideal situation, but you can also copy over your xray config to 2.1, set your config using 2.1, then copy it back to latest, though some blocks/items that may have been added in 2.2 and 2.3 will be unavailable for selecting.

**Comment by MichaelHillcox** [comment]
https://c.mikey.pro/data/mods/advanced-xray-neoforge-21.0.1.jar

Can you try this one and let me know if it resolves your issue?

**Comment by roflnomish** [comment]
yep that one seems to work perfectly so far, thanks for sorting it :)

**Comment by MichaelHillcox** [comment]
I'll release it tomorrow :D Glad that sorted it
